version: '3'

services:
    mysql:
        build:
            context: ./df-mysql
        container_name: mysql
        restart: always
        environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_USER=user
         - MYSQL_PASSWORD=password
         - MYSQL_DATABASE=wordpress
        volumes: 
          - mysql_vol:/var/lib/mysql
          
    wordpress:
        depends_on:
         - mysql
        build:
            context: ./df-wordpress
        container_name: wordpress
        restart: always
        environment:
         - WORDPRESS_DB_HOST=mysql:3306
         - WORDPRESS_DB_USER=user
         - WORDPRESS_DB_PASSWORD=password
         - WORDPRESS_DB_NAME=wordpress
        ports:
         - 8080:80
        volumes:
         - wordpress_vol:/var/www/html

volumes:
    mysql_vol: {}
    wordpress_vol: {}
